### ISSUE TITLE
CS2 Support for Query

### ISSUE THREAD

**Issue by NPetersenDK** [startersclan/PSSourceQuery#24]
Hi there!

I have been using the SourceQuery to many things the last like year and a half, to many things. It seems like there is some issues with it on CS2 (Source2) even tho the rcon and those things seems kinda the same. Is it something you want to look into making support for CS2/Source 2?

Basically it seems like the info type is making a lot of gibberish:
![image](https://github.com/startersclan/PSSourceQuery/assets/8342360/d1fc451e-99be-41f1-bbe4-00d40ffc07fe)

The players one seem to work slightly better:
![image](https://github.com/startersclan/PSSourceQuery/assets/8342360/d4eb3ccd-0d02-4809-9811-1294607739db)

Environment:
Debian Linux
PowerShell Core 7.3.9

Thanks,
Nikolaj

**Comment by leojonathanoh** [comment]
You're right, there's a bit of change with cs2 queries where it needs to trim off some control characters to parse the values correctly. Let me see what i can do over the next few days, will report back asap :)

**Comment by leojonathanoh** [comment]
good news :) managed to find out the problem, that cs2 changed to require challenge for `info` type, so i added that in an viola. 😄 

this is very useful for even myself, because I was scratching my head about this a few days ago. It isn't documented in the [wiki](https://developer.valvesoftware.com/wiki/Server_queries), but now we know 😸

**Comment by leojonathanoh** [comment]
Just wanted to drop a note here that cs2 seems to no longer publish the names of player names in `players` query, and `rules` query also no longer seems to return any rules. Unless they restore the old behavior, the only way to get these is by rcon. Perhaps, it is to combat against scrapers or attacks on query port.
